/**
 * Copyright 2018 California Institute of Technology.
 *
 * This source code is licensed under the APACHE 2.0 license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

// Main menu actions
export const SET_MAIN_MENU_TAB_INDEX = "SET_MAIN_MENU_TAB_INDEX";
export const SET_MAIN_MENU_OPEN = "SET_MAIN_MENU_OPEN";
export const SET_LAYER_INFO = "SET_LAYER_INFO";

// Chart Actions
export const SET_CHART_TRACK_SELECTED = "SET_CHART_TRACK_SELECTED";
export const SET_AXIS_VARIABLE = "SET_AXIS_VARIABLE";
export const INITIALIZE_CHART = "INITIALIZE_CHART";
export const SET_CHART_LOADING = "SET_CHART_LOADING";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const SET_CHART_DISPLAY_OPTIONS = "SET_CHART_DISPLAY_OPTIONS";
export const CLOSE_CHART = "CLOSE_CHART";
export const SET_CHART_FORM_ERROR = "SET_CHART_FORM_ERROR";
export const SET_CHART_FORM_VARIABLE_OPTIONS = "SET_CHART_FORM_VARIABLE_OPTIONS";
export const SET_CHART_WARNING = "SET_CHART_WARNING";

// Layer Actions
export const ADD_LAYER = "ADD_LAYER";
export const REMOVE_LAYER = "REMOVE_LAYER";
export const SET_INSITU_LAYER_COLOR = "SET_INSITU_LAYER_COLOR";
export const ZOOM_TO_LAYER = "ZOOM_TO_LAYER";
export const SET_TRACK_SELECTED = "SET_TRACK_SELECTED";
export const SET_TRACK_ERROR_ACTIVE = "SET_TRACK_ERROR_ACTIVE";
export const SET_LAYER_LOADING = "SET_LAYER_LOADING";
export const SET_INSITU_LAYER_TITLES = "SET_INSITU_LAYER_TITLES";

// Search Actions
export const SET_SEARCH_DATE_RANGE = "SET_SEARCH_DATE_RANGE";
export const SET_SEARCH_SELECTED_AREA = "SET_SEARCH_SELECTED_AREA";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_FACETS = "SET_SEARCH_FACETS";
export const SET_SEARCH_FACET_SELECTED = "SET_SEARCH_FACET_SELECTED";
export const CLEAR_SEARCH_FACET = "CLEAR_SEARCH_FACET";
export const SET_SEARCH_SORT_PARAM = "SET_SEARCH_SORT_PARAM";

// Map Actions
export const ENABLE_AREA_SELECTION = "ENABLE_AREA_SELECTION";
export const DISABLE_AREA_SELECTION = "DISABLE_AREA_SELECTION";
export const REMOVE_ALL_AREA_SELECTIONS = "CLEAR_AREA_SELECTION";
export const REMOVE_GEOMETRY_FROM_MAP = "REMOVE_GEOMETRY_FROM_MAP";
export const SET_DATE_INTERVAL = "SET_DATE_INTERVAL";

// Animation
export const SET_ANIMATION_OPEN = "SET_ANIMATION_OPEN";
export const SET_ANIMATION_PLAYING = "SET_ANIMATION_PLAYING";
export const STOP_ANIMATION = "STOP_ANIMATION";
export const STEP_ANIMATION = "STEP_ANIMATION";
export const SET_ANIMATION_START_DATE = "SET_ANIMATION_START_DATE";
export const SET_ANIMATION_END_DATE = "SET_ANIMATION_END_DATE";
export const SET_ANIMATION_DATE_RANGE = "SET_ANIMATION_DATE_RANGE";
export const FILL_ANIMATION_BUFFER = "FILL_ANIMATION_BUFFER";
export const EMPTY_ANIMATION_BUFFER = "EMPTY_ANIMATION_BUFFER";
export const CHECK_ANIMATION_BUFFER = "CHECK_ANIMATION_BUFFER";
export const CHECK_INITIAL_ANIMATION_BUFFER = "CHECK_INITIAL_ANIMATION_BUFFER";
export const CHECK_NEXT_FRAME = "CHECK_NEXT_FRAME";
export const DISPLAY_CURRENT_FRAME = "DISPLAY_CURRENT_FRAME";
export const SET_ANIMATION_SPEED = "SET_ANIMATION_SPEED";
